# Generated by Django 4.2.7 on 2023-12-03 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("host", models.CharField(max_length=128)),
                ("request", models.CharField(max_length=128)),
                ("username", models.CharField(max_length=128)),
            ],
            options={
                "indexes": [models.Index(fields=["host"], name="host_idx")],
            },
        ),
    ]
